### ISSUE TITLE
convert to public archive

### ISSUE THREAD

**Issue by ungoldman** [geobin-io/geobin.io#132]
Hello fellow geobineers!

I think this project _might_ be ready for the archive.

With your consent, may I go ahead and add a deprecation warning to the readme and archive the repo?

cc @aaronpk @aranasaurus @jyaganeh

**Comment by aranasaurus** [comment]
Sounds good to me! 👍

On March 27, 2022, GitHub ***@***.***> wrote:
> Hello fellow geobineers!
>
> I think this project might be ready for the archive.
>
> With your consent, may I go ahead and add a deprecation warning to the
> readme and archive the repo?
>
> cc @aaronpk <https://github.com/aaronpk>
> @aranasaurus <https://github.com/aranasaurus>
> @jyaganeh <https://github.com/jyaganeh>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/geobin-io/geobin.io/issues/132>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAB7PJBDTMKAQEB75L3TCLDVCDZG7ANCNFSM5RZQCFUQ>.
You are receiving this because you were mentioned.Message ID: <geobin-
***@***.***>

**Comment by jyaganeh** [comment]
Agreed. So long and farewell, geobin... ❤️ 

![](https://media1.giphy.com/media/kaBU6pgv0OsPHz2yxy/giphy.gif)

**Comment by ungoldman** [comment]
✅ e8f61d795eeb26b3a346062de87440be631fd2f2
